name: benchmarks
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  benchmark_harness: ^2.3.1

dev_dependencies:
  flutter_lints: ^6.0.0
