name: Review

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: main-${{ github.base_ref }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  review:
    name: Main Flutter PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Flutter
        uses: subosito/flutter-action@v2.21.0
        with:
          channel: 'stable'
          cache: true

      - name: Flutter Version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Check format
        run: dart format -l 120 --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze .
